In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

1.5.0


# Data set
From https://en.wikipedia.org/wiki/Iris_flower_data_set

TensorFlow’s high-level machine learning API (tf.contrib.learn) makes it easy to configure, train, and evaluate a variety of machine learning models. Here we use tf.contrib.learn to construct a neural network classifier and train it on the Iris data set to predict flower species based on sepal/petal geometry.

### 3 types of Iris Flowers:

<img src="AI_TF_Estimators/files/irisSetosa.jpg" style="width: 200px; float: auto;" title="irisSetosa"/> 
<img src="files/Iris_versicolor_2.jpg" style="width: 200px; float: auto;" title="Iris_versicolor_2"/> 
<img src="files/iris_virginica_virginica_lg.jpg" alt="Drawing" style="width: 200px; float: auto;" title="iris_virginica"/>

1. Iris Setosa
2. Iris Versicolour
3. Iris Virginica

**Data Columns:**
* sepal length in cm
* sepal width in cm
* petal length in cm
* petal width in cm

<img src="files/IrisFlowersData.png" style="width: auto" title="SampleIrisFlowersData"/> 


# 1. Gathering data

This Iris data set contains 120 rows of data from each of three related Iris species: Iris setosa, Iris virginica, and Iris versicolor.

# 2. Data Preparation

In the below cell, we load the training and test sets into Datasets using the load_csv_with_header() method in learn.datasets.base. The load_csv_with_header() method takes three required arguments:

* filename, which takes the filepath to the CSV file
* target_dtype, which takes the numpy datatype of the dataset's target value.
* features_dtype, which takes the numpy datatype of the dataset's feature values.

Here, the target (the value you're training the model to predict) is flower species, which is an integer from 0–2, so the appropriate numpy datatype is np.int:

Also, training_set.data and training_set.target contain the feature data and target values for the training set, respectively, and test_set.data and test_set.target contain feature data and target values for the test set.

In [2]:
# Data files
IRIS_TRAINING = "P:/Machine Learning/AI_TF_Estimators/files/iris_flower_training.csv"
IRIS_TEST = "P:/Machine Learning/AI_TF_Estimators/files/iris_flower_test.csv"

# Load datasets.
training_set = tf.contrib.learn.datasets.base.load_csv_with_header(
    filename=IRIS_TRAINING,
    target_dtype=np.int,
    features_dtype=np.float32)
test_set = tf.contrib.learn.datasets.base.load_csv_with_header(
    filename=IRIS_TEST,
    target_dtype=np.int,
    features_dtype=np.float32)

print(training_set.data)

print(training_set.target)

[[6.4 2.8 5.6 2.2]
 [5.  2.3 3.3 1. ]
 [4.9 2.5 4.5 1.7]
 [4.9 3.1 1.5 0.1]
 [5.7 3.8 1.7 0.3]
 [4.4 3.2 1.3 0.2]
 [5.4 3.4 1.5 0.4]
 [6.9 3.1 5.1 2.3]
 [6.7 3.1 4.4 1.4]
 [5.1 3.7 1.5 0.4]
 [5.2 2.7 3.9 1.4]
 [6.9 3.1 4.9 1.5]
 [5.8 4.  1.2 0.2]
 [5.4 3.9 1.7 0.4]
 [7.7 3.8 6.7 2.2]
 [6.3 3.3 4.7 1.6]
 [6.8 3.2 5.9 2.3]
 [7.6 3.  6.6 2.1]
 [6.4 3.2 5.3 2.3]
 [5.7 4.4 1.5 0.4]
 [6.7 3.3 5.7 2.1]
 [6.4 2.8 5.6 2.1]
 [5.4 3.9 1.3 0.4]
 [6.1 2.6 5.6 1.4]
 [7.2 3.  5.8 1.6]
 [5.2 3.5 1.5 0.2]
 [5.8 2.6 4.  1.2]
 [5.9 3.  5.1 1.8]
 [5.4 3.  4.5 1.5]
 [6.7 3.  5.  1.7]
 [6.3 2.3 4.4 1.3]
 [5.1 2.5 3.  1.1]
 [6.4 3.2 4.5 1.5]
 [6.8 3.  5.5 2.1]
 [6.2 2.8 4.8 1.8]
 [6.9 3.2 5.7 2.3]
 [6.5 3.2 5.1 2. ]
 [5.8 2.8 5.1 2.4]
 [5.1 3.8 1.5 0.3]
 [4.8 3.  1.4 0.3]
 [7.9 3.8 6.4 2. ]
 [5.8 2.7 5.1 1.9]
 [6.7 3.  5.2 2.3]
 [5.1 3.8 1.9 0.4]
 [4.7 3.2 1.6 0.2]
 [6.  2.2 5.  1.5]
 [4.8 3.4 1.6 0.2]
 [7.7 2.6 6.9 2.3]
 [4.6 3.6 1.  0.2]
 [7.2 3.2 6.  1.8]
 [5.  3.3 1.4 0.2]
 [6.6 3.  4.4 1.4]
 [6.1 2.8 4.

# 3. Choose a Model

Fit the DNNClassifier to the Iris Training Data and use training_set.data and training_set.target to train your model, and in "Evaluate Model Accuracy," we'll use test_set.data and test_set.target.

tf.contrib.learn offers a variety of predefined models, called Estimators, which we can use "out of the box" to run training and evaluation operations on your data. Here, we'll configure a Deep Neural Network Classifier model to fit the Iris data. Using tf.contrib.learn, we can instantiate your tf.contrib.learn.DNNClassifier with just a couple lines of code:

In [3]:
# Specify that all features have real-value data
feature_name = "flower_features"
feature_columns = [tf.feature_column.numeric_column(feature_name, 
                                                    shape=[4])]
classifier = tf.estimator.LinearClassifier(feature_columns=feature_columns,
                                           n_classes=3,
                                           model_dir="/tmp/iris_model")

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/iris_model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001539CBF6C88>, '_task_type': 'worker', '_task_id': 0, '_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [4]:
# # Define the test inputs
def input_fn(dataset):
    def _fn():
        features = {feature_name: tf.constant(dataset.data)}
        label = tf.constant(dataset.target)
        return features, label
    return _fn

print(input_fn(training_set)())

# raw data -> input function -> feature columns -> modelx

({'flower_features': <tf.Tensor 'Const:0' shape=(120, 4) dtype=float32>}, <tf.Tensor 'Const_1:0' shape=(120,) dtype=int32>)


# 4. Train the Model

Here, we Fit the DNNClassifier to the Iris Training Data

Now that you've configured your DNN classifier model, we can fit it to the Iris training data using the fit method. Pass get_train_inputs as the input_fn, and the number of steps to train (here, 2000):

In [5]:
# Fit model.
classifier.train(input_fn=input_fn(training_set),
               steps=2000)
print('fit executed successful')

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Restoring parameters from /tmp/iris_model\model.ckpt-7000
INFO:tensorflow:Saving checkpoints for 7001 into /tmp/iris_model\model.ckpt.
INFO:tensorflow:loss = 6.634166, step = 7001
INFO:tensorflow:global_step/sec: 1375.62
INFO:tensorflow:loss = 6.6103373, step = 7101 (0.074 sec)
INFO:tensorflow:global_step/sec: 1732.83
INFO:tensorflow:loss = 6.5870285, step = 7201 (0.058 sec)
INFO:tensorflow:global_step/sec: 1690.4
INFO:tensorflow:loss = 6.5642166, step = 7301 (0.058 sec)
INFO:tensorflow:global_step/sec: 1734.46
INFO:tensorflow:loss = 6.5418906, step = 7401 (0.059 sec)
INFO:tensorflow:global_step/sec: 1734.55
INFO:tensorflow:loss = 6.5200305, step = 7501 (0.057 sec)
INFO:tensorflow:global_step/sec: 1917.88
INFO:tensorflow:loss = 6.498618, step = 7601 (0.052 sec)
INFO:tensorflow:global_step/sec: 1955.66
INFO:tensorflow:loss = 6.4776373, step = 7701 (0.051 sec)
INFO:tensorflow:global_step/sec: 2144.74
INFO:tensorflow:loss = 6.457

# 5. Evaluate  Model Accuracy

In [6]:
accuracy_score = classifier.evaluate(input_fn=input_fn(test_set), 
                                     steps=2000)["accuracy"]
print('\nAccuracy: {0:f}'.format(accuracy_score))

INFO:tensorflow:Starting evaluation at 2018-02-12-02:44:56
INFO:tensorflow:Restoring parameters from /tmp/iris_model\model.ckpt-9000
INFO:tensorflow:Evaluation [200/2000]
INFO:tensorflow:Evaluation [400/2000]
INFO:tensorflow:Evaluation [600/2000]
INFO:tensorflow:Evaluation [800/2000]
INFO:tensorflow:Evaluation [1000/2000]
INFO:tensorflow:Evaluation [1200/2000]
INFO:tensorflow:Evaluation [1400/2000]
INFO:tensorflow:Evaluation [1600/2000]
INFO:tensorflow:Evaluation [1800/2000]
INFO:tensorflow:Evaluation [2000/2000]
INFO:tensorflow:Finished evaluation at 2018-02-12-02:44:57
INFO:tensorflow:Saving dict for global step 9000: accuracy = 0.96666664, average_loss = 0.06093761, global_step = 9000, loss = 1.8281283

Accuracy: 0.966667


# 6. Exporting a model for serving prediction

In [13]:
def serving_input_fn():
        inputs = {'flower_features': tf.placeholder(tf.float32, [4])}
        return tf.estimator.export.ServingInputReceiver(inputs, inputs)

classifier.export_savedmodel(export_dir_base="/tmp/iris_model", serving_input_receiver_fn=serving_input_fn)

INFO:tensorflow:Signatures INCLUDED in export for Classify: None
INFO:tensorflow:Signatures INCLUDED in export for Regress: None
INFO:tensorflow:Signatures INCLUDED in export for Predict: ['predict']
INFO:tensorflow:Signatures EXCLUDED from export because they cannot be be served via TensorFlow Serving APIs:
INFO:tensorflow:'serving_default' : Classification input must be a single string Tensor; got {'flower_features': <tf.Tensor 'Placeholder:0' shape=(4,) dtype=float32>}
INFO:tensorflow:'classification' : Classification input must be a single string Tensor; got {'flower_features': <tf.Tensor 'Placeholder:0' shape=(4,) dtype=float32>}
INFO:tensorflow:Restoring parameters from /tmp/iris_model\model.ckpt-9000
INFO:tensorflow:Assets added to graph.
INFO:tensorflow:No assets to write.
INFO:tensorflow:SavedModel written to: b"/tmp/iris_model\\temp-b'1518411638'\\saved_model.pb"


b'/tmp/iris_model\\1518411638'